site_name: ReJSON - a JSON data type for Redis
site_url: https://goodformcode.com
site_favicon: 'images/favicon.png'
repo_url: https://github.com/goodform/rejson
repo_name: goodform/rejson
theme: material

extra:
  palette:
    primary: 'indigo'
  logo: 'images/logo.svg'
  social:
    - type: 'github'
      link: 'https://github.com/goodform'

markdown_extensions:
  - codehilite

pages:
    - 'Quickstart': 'index.md'
    - 'Commands': 'commands.md'
    - 'Path syntax': 'path.md'
    - 'Performance': 'performance.md'
    - 'RAM usage': 'ram.md'
    - 'Developer notes': 'developer.md'

google_analytics:
    - 'UA-92003007-8'
    - 'auto'
